### ISSUE TITLE
Getting paired with the same people

### ISSUE THREAD

**Issue by lainekendall** [thwidge/pairing-bot#6]
### Issue
I keep getting paired with people I have already been paired with

### Possible solutions
- the Pairing Bot could store some sort of history to give lower weights to already paired combinations so that people have a higher chance of pairing with a new person

**Comment by marenbeam** [comment]
This is great! Thanks for submitting an issue @lainekendall :)

My thoughts:
* I think that the "mix and match" function is probably working correctly, **but**
  * Even if 30 people are signed up for Pairing Bot, there may only be a few people scheduled for matches on a given day, **thus**
  * After a few weeks, it's particularly likely to get re-matched with a person on that day

I'm super into giving Pairing Bot a memory, and prioritizing matches that haven't already happened. However, I'd like to do it in the simplest way possible. Do you have any thoughts about what that might look like? If not, that's totally fine! The database schema currently looks like this:
* recurser
  * email [string]
  * id [int]
  * isSkippingTomorrow [bool]
  * name [string]
  * schedule
    * monday [bool]
    * tuesday [bool]
    * wednesday [bool]
    * thursday [bool]
    * friday [bool]
    * saturday [bool]
    * sunday [bool]

If you have any thoughts about ways we could do this, let me know! :)

**Comment by dwinston** [comment]
Hi @marenbeam, how about using a "subcollection" (the name used by [Firestore](https://cloud.google.com/firestore/docs/data-model#hierarchical-data); I have no experience using Firestore -- I just perused the docs)? My initial thought is to have a subcollection `lastPaired` inside each `recurser` doc, where each doc of `lastPaired` has two keys, `recurserId` (a reference to a `recurser.id`) and `date` (I guess a date type if there is one, otherwise a string of form "YYYY-MM-DD"?).

And then adding a command to the bot one can issue from zulip like `ipairedwith @**Maren Beam (she) (SP2'19)** 2019-11-19` to add that document to my subcollection. This date-based ledger allows config for when to be paired again with someone, like the default could be after two weeks (if pairing bot finds no one else), but one could change to "never", "one week", etc.

**Comment by dwinston** [comment]
@marenbeam btw I would be interested in "pairing" on this (I don't know Go/Firebase at all, so it would resemble "watching" more than "pairing").

**Comment by marenbeam** [comment]
This is a great plan @dwinston :) Thanks so much for putting the time and effort into writing it out!

Unfortunately, Pairing Bot’s gonna get a python re-write, and switch to SQLite as the db — so the Go/Firestore specific parts of this soon won’t apply. But your plan for the database sounds great! I think we should implement it that way.

For anyone reading this — my hope in rewriting pairing bot entirely in python is that it’ll make it easier for more people to contribute and help maintain as time goes on. Also, I don’t know python and I’d like to!

**Comment by dwinston** [comment]
Yay!

I *do* feel competent with both Python and SQLite, so your hope works for me! :)

**Comment by thwidge** [comment]
No longer moving to Python and SQLite, sticking with Go and Firestore. Closing for now, since solving this matching problem has proven to be non-trivial for [chat bot](https://github.com/thechutrain/rc-coffee-chats). I'm willing to revisit!
